FLAKE_DIR="@flakeDir@"

cd "$FLAKE_DIR"

echo ":: update flake.."
nix flake update

if git diff --quiet flake.lock; then
  echo ":: lock file already up to date. abort.."
  exit 0
fi

echo ":: test flake.."

HOST="$(hostname)"
USER_NAME="$(whoami)"

if ! nix build --dry-run ".#nixosConfigurations.${HOST}.config.system.build.toplevel" || \
   ! nix build --dry-run ".#homeConfigurations.${USER_NAME}@${HOST}.activationPackage"; then
  echo ":: an error occured. rollback.." >&2
  git checkout flake.lock
  notify-send -u critical "Fup" "update failed!"
  exit 1
fi

echo ":: collect changed inputs.."
UPDATED_INPUTS=$(git show HEAD:flake.lock | jq -r --slurpfile new flake.lock '
  (.[0].nodes // {}) as $o |
  ($new[0].nodes // {}) as $n |
  [
    $n | keys[] | select(
      . != "root" and
      $n[.].locked.rev != null and
      $o[.].locked.rev != null and
      $n[.].locked.rev != $o[.].locked.rev
    )
  ] | map("- " + .) | join("\n")
')

COMMIT_MSG="lock: auto-update"
if [ -n "$UPDATED_INPUTS" ]; then
  COMMIT_BODY="Updated:
$UPDATED_INPUTS

Automated commit generated by fup."
else
  COMMIT_BODY="Automated commit generated by fup."
fi

git commit flake.lock -m "$COMMIT_MSG" -m "$COMMIT_BODY"

echo ":: push new inputs.."
BRANCH="$(git branch --show-current)"
if git push origin "$BRANCH"; then
  notify-send "Fup" "update successfull."
  echo ":: complete."
else
  notify-send -u critical "Fup" "update completed but not pushed!"
  exit 1
fi
